docker: &docker
  encoding: utf8mb4
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  # CircleCIではAPP_DATABASE_HOST="127.0.0.1"
  host:  <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>

no_docker: &no_docker
  encoding: utf8
  username: root
  password:
  socket: /tmp/mysql.sock

no_docker_production: &no_docker_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

<% db_type = ENV.fetch("DB_TYPE") { 'no_docker' } %>
default: &default
  <% if db_type == 'docker' %>
  <<: *docker
  <% else %>
  <<: *no_docker
  <% end %>
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cloud_reminder_development

test:
  <<: *default
  database: cloud_reminder_test

production:
  <<: *default
  <% unless db_type == 'docker' %>
  <<: *no_docker_production
  <% end %>
  database: cloud_reminder_production
