docker: &docker
  encoding: utf8mb4
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db

no_docker: &no_docker
  encoding: utf8
  username: root
  password:
  socket: /tmp/mysql.sock

default: &default
  <<: *<%= ENV.fetch("DB_TYPE") { 'no_docker' } %>
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cloud_reminder_development

test:
  <<: *default
  database: cloud_reminder_test
  # host: <%= ENV.fetch("APP_DATABASE_HOST") { 'db' } %>

production:
  <<: *default
  database: cloud_reminder_production
